### ISSUE TITLE
Consider naming functions/variables to allow some flexibility

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/patternfly-next#126]
Just mulling over some of the upcoming changes & wondering if using functions to generate named patterns was reasonable.  For example, the are some who love BEM, some who dislike, and most just land in the middle somewhere.

Any thoughts on variables or functions to allow the consumer to tweak:

```CSS 
// easy win maybe
$pf-prefix: 'pf-'

.#{$pf-prefix}widget {
 // styles...
}

// more complicated, to generate, default would create:
// .pf-widget__body--extra 
.#{$pf-prefix}widget${elem('body')}#{mod('extra')} {
 // styles...
}
// but someone could override the functions elem() and mod() to create:
.pf-widget-body-extra
// etc.

// or could just use:
.#{bem-name($pf-prefix, 'widget', 'body', 'extra')} {
  // styles 
}
// accomplish the same, but allow users to override 1 function & alter 
// the output template.
```
This would definitely allow the default to go BEM, users to consume if they desire, but also to alter a bit if it better fits an existing schema.

Thanks for considering!
