### ISSUE TITLE
Investigate a configuration first method to create modifiers and states

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#273]
We want to look into redefining variables instead of overwritting CSS for modifiers and states.

For example:
```scss
  &.pf-m-secondary {
    --pf-c-button--Color: var(--pf-c-button--m-secondary--Color);
   // instead of:
    color: var(--pf-c-button--m-secondary--Color);
}
```

Once we do this let's have a discussion with the CSSers and the people contributing to see if they like it.

cc/ @mattnolting 

--------

A couple of other things you can do alongside refactoring this CSS, since we'll be going through each component and will need to do these things at some point anyways...

* make sure we're using components in components properly. For example in .pf-c-modal-box, we have `.pf-c-modal-box__close` that wraps `.pf-c-button`. I think it's fine to remove `.pf-c-modal-box__close` and just use `.pf-c-button`. Also if you see an instance of a button or title that isn't using `.pf-c-button/.pf-c-title`, and it could be, feel free to update that.
* see if we can consolidate vars in a way that makes sense
    * if we have 4 vars for all sides of padding, when those values are all the same and if one changes, they should all change, just use a single var
* just see if there are any small improvements you can make to the html/css. Unused vars, unnecessary CSS, refactors that make sense and might make the code lighter.

This is all just for small, obvious adjustments. If any of this work is substantial or needs group input, don't worry about it and open a separate issue to address it.
