### ISSUE TITLE
Improve forms

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#289]
This is related to #200 and be done in parallel . 

The form component needs some adjustments to follow conventions with the rest of the system:

1 Transform the variable overwrite to property overwrite. For example:
```scss
&:hover {
      --pf-c-form__input--BorderSize: var(--pf-c-form__input--hover--BorderSize);
}
// should be
&:hover {
     border-size: var(--pf-c-form__input--hover--BorderSize);
}
```

2 Write correct variable names for modifiers. For example:
```scss
--pf-c-form--error--Color
// Should be
--pf-c-form--m-error--Color
}
```
3 Go through the color variables and make sure we are using the correct color global variables.

5 Extract form controls into individual components
Controls like radios, checkboxes or inputs should be extracted to single components. That way they can be used outside the form component like a checkbox on a table.
The form component should define form elements like labels and fieldsets, and form layouts and consume those controls components on a demo.
