### ISSUE TITLE
Evaluate PostCSS-preset-env to see if IE11 support is feasible

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-next#450]
From their site - https://preset-env.cssdb.org/ lets you convert modern CSS into something most browsers can understand, determining the polyfills you need based on your targeted browsers or runtime environments.

Evaluate whether or not we can include a recommendation to have downstream consumers use this (or is there a sample application we should provide with configuration samples to do this).  See if IE11 support is attainable using this as a build tool.

**Comment by dmiller9911** [comment]
Example config/script
```js
const presetEnv = require('postcss-preset-env');
const postcss = require('postcss');
const fs = require('fs');
const cssvariables = require('postcss-css-variables');
const path = require('path');

const css = fs.readFileSync(
  path.resolve(__dirname, './dist/patternfly.css'),
  'utf8'
);

postcss([
  presetEnv({
    stage: 0,
    features: {
      'custom-properties': false
    },
    autoprefixer: { grid: true }
  }),
  cssvariables()
])
  .process(css, {
    from: path.resolve(__dirname, './dist/patternfly.css'),
    to: path.resolve(__dirname, './dist/paternfly.old.css')
  })
  .then(result => {
    fs.writeFileSync(
      path.resolve(__dirname, './dist/paternfly.old.css'),
      result.css
    );
  });

```
this still has some issues with handling a few variables, but gets it 90%.  It fails when it has something like this
```css
:root {
  --global-color: #fff;
  --global-color-hover: green;
}
.btn {
  --btn-color: var(--global-color);
  --btn-color-hover: var(--global-color-hover);
  color: var(--btn-color);
}
.btn:hover {
  color: var(--btn-color-hover); // this works
}
.btn.hover {
  color: var(--btn-color-hover); // this does not work
}
```
